#!/bin/sh
# One-command local run of the unified INSIGHT image.
#
#   sh deploy/run.sh            # build + up (foreground)
#   sh deploy/run.sh -d         # build + up (detached)
#   sh deploy/run.sh down       # stop and remove containers
#   sh deploy/run.sh down -v    # stop and wipe data volumes
#
# If secrets are not already present in the environment, this script writes
# freshly generated random values to ./.env (gitignored) on first run and
# reuses them afterwards. Pass GEN_SECRETS=1 to force-regenerate them.
#
# For plain-HTTP local use, AUTH_SECURE_COOKIE and *_CSRF_SECURE default to
# false (see deploy/compose.yaml). Behind HTTPS, set these to true in .env.
set -eu

repo_root=$(CDPATH= cd "$(dirname "$0")/.." && pwd)
cd "$repo_root"
compose_file="deploy/compose.yaml"

# Reuse previously generated local secrets so admin login stays stable across runs.
# GEN_SECRETS=1 skips this to force a fresh set.
env_file="$repo_root/.env"
if [ "${GEN_SECRETS:-0}" != "1" ] && [ -f "$env_file" ]; then
  set -a && . "$env_file" && set +a
fi

need_secret() { name="$1"; [ -z "$(printenv "$name" 2>/dev/null || true)" ]; }

gen_secret() { python3 -c 'import secrets; print(secrets.token_urlsafe('"$1"'))'; }

ensure_secrets() {
  env_file="$repo_root/.env"
  changed=0
  write_env=0
  [ -e "$env_file" ] || write_env=1
  [ "${GEN_SECRETS:-0}" = "1" ] && write_env=1

  set -- \
    AUTH_JWT_SECRET 64 \
    AUTH_ADMIN_PASSWORD 24 \
    ADD_NEW_PATIENT_CSRF_SECRET 32 \
    DIAGNOSIS_CSRF_SECRET 32 \
    SEVERITY_CSRF_SECRET 32 \
    MEDICAL_HISTORY_CSRF_SECRET 32 \
    DDI_SERVICE_AUTH_SECRET 32 \
    SUICIDE_RISK_CSRF_SECRET 32

  while [ "$#" -gt 0 ]; do
    name="$1"; bits="$2"; shift 2
    if need_secret "$name"; then
      eval "export $name=\$(gen_secret $bits)"
      changed=1
    fi
  done

  if [ "$write_env" = "1" ] || [ "$changed" = "1" ]; then
    {
      echo "# Generated by deploy/run.sh for local unified runs. Do not commit."
      echo "AUTH_JWT_SECRET=$AUTH_JWT_SECRET"
      echo "AUTH_ADMIN_PASSWORD=$AUTH_ADMIN_PASSWORD"
      echo "AUTH_SECURE_COOKIE=false"
      echo "ADD_NEW_PATIENT_CSRF_SECRET=$ADD_NEW_PATIENT_CSRF_SECRET"
      echo "ADD_NEW_PATIENT_CSRF_SECURE=false"
      echo "DIAGNOSIS_CSRF_SECRET=$DIAGNOSIS_CSRF_SECRET"
      echo "DIAGNOSIS_CSRF_SECURE=false"
      echo "SEVERITY_CSRF_SECRET=$SEVERITY_CSRF_SECRET"
      echo "MEDICAL_HISTORY_CSRF_SECRET=$MEDICAL_HISTORY_CSRF_SECRET"
      echo "DDI_SERVICE_AUTH_SECRET=$DDI_SERVICE_AUTH_SECRET"
      echo "SUICIDE_RISK_CSRF_SECRET=$SUICIDE_RISK_CSRF_SECRET"
    } > "$env_file"
    echo "Wrote local secrets to $env_file"
    echo "  -> seeded admin login: Admin / $AUTH_ADMIN_PASSWORD"
  fi
}

case "${1:-up}" in
  up)
    ensure_secrets
    shift_args=""
    [ "${1:-}" = "-d" ] && shift_args="-d"
    exec docker compose -f "$compose_file" up --build ${shift_args:+"$shift_args"}
    ;;
  down)
    exec docker compose -f "$compose_file" down "${2:-}"
    ;;
  logs)
    exec docker compose -f "$compose_file" logs "${2:-}"
    ;;
  *)
    echo "usage: sh deploy/run.sh [up|-d|down [down -v]|logs]" >&2
    exit 2
    ;;
esac
